name: Extract Zip File
on:
  workflow_dispatch:

jobs:
  extract_job:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Zip from Release
        run: |
          # Is line mein humne aapke exact file aur repo names use kiye hain
          curl -L -o Web-To-Native.zip https://github.com/${{ github.repository }}/releases/download/v1.0/Web-To-Native.zip
 - name: Unzip Files
        run: |
          unzip Web-To-Native.zip -d ./
          # Folder ke andar ki saari files ko bahar main home par move karne ke liye:
          mv Web-To-Native/* ./ || true
          rm -rf Web-To-Native
          rm Web-To-Native.zip
 
